### ISSUE TITLE
Extend section on “Customizing PDF output”

### ISSUE THREAD

**Issue by infotexture** [dita-ot/docs#70]
The current [Customizing PDF output](http://www.dita-ot.org/2.2/user-guide/dita2pdf-customization.html) topic should be expanded to a section with additional subtopics, including:

- [x] Overview of customization approaches, with pros, cons & recommendations for each approach:
    1. Editing default `org.dita.pdf2` files in place — **why not to!**
    2. Placing custom files in `org.dita.pdf2/Customization` folders, editing `custom.xsl.orig`
    3. Specifying remote customization folders via `customization.dir`
- [x] _Best practices:_ Creating custom PDF plug-ins
    * `custom.xsl` vs. replicating `org.dita.pdf2` folder structure
    * Duplicating entire `org.dita.pdf2` stylesheets vs. individual templates
    * Migrating custom PDF plug-ins to new DITA-OT versions (see [comments](https://github.com/dita-ot/docs/issues/29#issuecomment-177595491) in #29)
- [x] Link to the PDF plugin generator #57
- [x] Relevant content from `pdf2` ReadMe files #69
- [x] Migrating PDF customization folders to plugins #43

The task content from the current topic should be preserved as a topic within the new section.

**Comment by keberlein** [comment]
Assign this one to me.
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 2/11/2016 5:57 AM, Roger Sheen
      wrote:
    
    
      The current Customizing
          PDF output topic should be expanded to a section with
        additional subtopics, including:
      
        
           Link to the PDF plugin generator #57
        
        
           Relevant content from pdf2
          ReadMe files #69
        
      
      The task content from the current topic should be preserved as
        a topic within the new section.
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by infotexture** [comment]
OK, will do, thanks. 

I'm preparing a new topic on the generator for #57, so I'll handle that part.

**Comment by keberlein** [comment]
I am working on this. It's a bit challenging, because logically it needs to build on the previous chapter about DITA-OT plug-ins -- and that set of topics could use some work.
